name: Code Review Workflow

on: [pull_request]

jobs:
  review_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Ollama GitHub Code Reviewer
        uses: brobles82/ollama-github-reviews@v0.0.1
